In [9]:
import pandas as pd
import numpy as np
from scipy.stats import skew, kurtosis

In [10]:
data = pd.read_csv("/content/Q9_a (1).csv")
data.head()

   Index  speed  dist
0      1      4     2
1      2      4    10
2      3      7     4
3      4      7    22
4      5      8    16

In [11]:
speed = data['speed']
distance = data['dist']

In [13]:
# Calculate skewness
skewness_speed = skew(speed)
skewness_distance = skew(distance)

# Calculate kurtosis
kurtosis_speed = kurtosis(speed)
kurtosis_distance = kurtosis(distance)

# Print the results
print("Skewness:")
print("Speed:", skewness_speed)
print("Distance:", skewness_distance)

print("Kurtosis:")
print("Speed:", kurtosis_speed)
print("Distance:", kurtosis_distance)

Skewness:
Speed: -0.11395477012828319
Distance: 0.7824835173114966
Kurtosis:
Speed: -0.5771474239437371
Distance: 0.24801865717051808

In [14]:
car = pd.read_csv("/content/Q9_b (1).csv")
car.head()

   Unnamed: 0          SP         WT
0           1  104.185353  28.762059
1           2  105.461264  30.466833
2           3  105.461264  30.193597
3           4  113.461264  30.632114
4           5  104.461264  29.889149

In [18]:

# Extract the required columns for SP and WT
SP = car['SP']
WT = car['WT']

# Calculate skewness
skewness_SP = skew(SP)
skewness_WT = skew(WT)

# Calculate kurtosis
kurtosis_SP = kurtosis(SP)
kurtosis_WT = kurtosis(WT)

# Print the results
print("Skewness:")
print("SP:", skewness_SP)
print("WT:", skewness_WT)

print("Kurtosis:")
print("SP:", kurtosis_SP)
print("WT:", kurtosis_WT)

Skewness:
SP: 1.5814536794423764
WT: -0.6033099322115126
Kurtosis:
SP: 2.7235214865269244
WT: 0.8194658792266849